apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ssacpb9x0-nodejs 
  janus-idp.io/tekton: ssacpb9x0-nodejs
  backstage.io/kubernetes-id: ssacpb9x0-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ssacpb9x0-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml